- name: Create docker folder
  file:
    path: docker-folder
    state: directory

- name: Clone the tomcat repository
  git:
    repo: "http://{{ username }}:{{ password }}@54.215.47.70/gitlab/piajobelle1/Tomcat.git"
    dest: docker-folder

- name: Download WAR file
  get_url:
    url: "http://54.215.47.70/nexus/service/local/repositories/snapshots/content/DTSActivity/CurrencyConverter/1.0/CurrencyConverter-1.0.war"
    dest: docker-folder/Resources
    mode: 0755
    url_password: "{{ password }}"
    url_username: "{{ username }}"